name: "assert base64_decoding('InvalidBase64!\n') == ([-1], '')"
limit: 2000
memory_size: 0x1000
memory_mapped_io:
  0x80: [83, 71, 86, 115, 98, 71, 56, 103, 100, 50, 57, 121, 98, 71, 81, 104, 10]
  0x84: []
reports:
  - name: Check results
    slice: all
    filter:
      - state
    view: |
      {pc}: {instruction} {pc:label}
      numio[0x80]: {io:0x80:dec}
      numio[0x84]: {io:0x84:dec}
      symio[0x80]: {io:0x80:sym}
      symio[0x84]: {io:0x84:sym}
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [72,101,108,108,111,32,119,111,114,108,100,33]
      symio[0x80]: "" >>> ""
      symio[0x84]: "" >>> "Hello world!"